# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ca8c6405fdac16a8872c92b9a7001444d92cb54c61a0aa9d25825367469ccd8e79f0ccec0ace69828cf56c3f3d68a01c6e52ea4f06eb295332fab429837d6d8c
  aws_access_key_id: "AKIAJXGTZNU7KUQE7C6Q"
  aws_secret_access_key: "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"
  s3_bucket_name: "feelingjy-local"
  tokbox:
    api_key: '45994012'
    secret: 'b5878c76bc661964016bcbd2e8b8564b726886e6'
  alipay:
    app_id: '2017122801301031'
    # api_url: 'https://openapi.alipaydev.com/gateway.do'
    api_url: 'https://openapi.alipay.com/gateway.do'
    app_private_key: "-----BEGIN RSA PRIVATE KEY-----\nMIIEpQIBAAKCAQEAtBKIAzsfy30soLehWmiyvqrkXgQxHW+Vmm0TFEedEoEsJ1Be\nABDm/++CgwZsbeUgQrd4er0ly/Lk+4xNwOcZlBnKVhpl0I34uHypjiXIQdCItiTY\nGKElduBtrdlzpZHPLmtMPBKJmrLgmjGAON7p4hIeerO7uazl+Uzq4ult23yoeAFV\n7cUMYpHBDh/XgxlQg/n7FITqCCIdmS2Z+Ii8FYaqItBJGBcDTevl6XRGsCaLcpzO\nmc1T68IKceykqKHLTCi9R//NBC8m1GpvzYKyAGktm03hcNviFDediGSkzbR8Clyb\nIaAR/oKXqYA4QkhRWWiwQHOpRFqIxdZc18gR9QIDAQABAoIBAAg0V/IdvYMd/uyL\nsVRXNN2vF5yZAEvhC6XvllD0OlnffM2FweKq4nuCxCWII2SWbfPcPCcLey9hr8Eu\nUVSasvWmfyuRJFZuQYjWVTteyVMGV1RFNXtZzEUwUI79O2Gt1Qy+YsjR52cfA1DD\nNJ5iubFNNgpNKh55nDjRoloYXKMFZWEY4YDGOkNL4b63TCEpkWFvc10kdOORdB7k\ngBRx0w9O9F69lY/zoHfKaojLCeqK0OU5wb54vsK8YqhMOvqlYToTKmvld/ZKKO4n\nmJn8f9yS16GrNDxJZbnsouHFX3khfrFrFO1qfpTk/p6Yxj39cplTJhl/7rT1p4ZI\nc/RaEzkCgYEA50f1S52rxR+i/K1Sdlhhj/BeTmcLmng0Gt0nU9Iq0mvCTJExqZdO\nACqW6+HDdjszSmY6OC1hKrbE7Ebj3tcV5N4Ibcpn5tsasW+g5q9IHXQC3tdXRtMX\n3sFzZNbP7gknBQy/ZbAYwAmZZRYudcG+zrv0EZgrn9wJ0vYnconwAk8CgYEAx1F1\n9JDvsch+MhDPMXWsu1i5RQ+RfCQ4HGzA6wUcSI8EWaa2xh92KGVxPafgl7y7Z3QR\nDsYOxwBACrvY/teEXdFfMkAL0qJL6MOQM2ujMCX5PLe3rxCCKylpckWI8pEHkHYA\nzSYh+8LhAkHAzGGzIExflCRrryOyk4X0VsYKKnsCgYEAxXkeSwr7/9qsWlxOvXdn\nDfRpQT4gnSqnKozLqHkZUQLrKl8KbUggNGoo5IymTMvtVkgEy7SLc2IMr8UziTBS\npFCkF8IrhuRrXTb3xh/BTkygqs5o2bMhfXPlaCM19INiCqDAxz1dVJKdo78VujvM\nBE5c7azlCqBgzvyX3+dAw2cCgYEAlqzvNaYHfWdqduCcMPCbVrlYvWtqeOVMgbh5\nEnG3kuaCzF8qVpXcFeex9oEdWLf1F9z3NCrnauq2fybIgMZdqyqnA27FQUMtjVWh\ngi3BnJloU80yj6Y0MPrKWvdT8sNOa5e5PVyxXghRXwpj/F1zM1xo+K2btjePPNSM\nBLkLYFcCgYEAg8BDZaEUR+yI6tFDY6VtwpdmByhLvDSnCg1MZ9QZlFlvCHjmzq8o\nbZTjxrBgR9eFrYKHdYslxI51kcsn3LruO4nowB0h4kLfetLUPZ+5dMhBF2H1MHrl\n+7jLbuEY+t8O2Cf+63ppkB3W43Akt2bdVw8EWFz3gP1SOPOyo91DiSM=\n-----END RSA PRIVATE KEY-----"
    alipay_public_key: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtBKIAzsfy30soLehWmiy\nvqrkXgQxHW+Vmm0TFEedEoEsJ1BeABDm/++CgwZsbeUgQrd4er0ly/Lk+4xNwOcZ\nlBnKVhpl0I34uHypjiXIQdCItiTYGKElduBtrdlzpZHPLmtMPBKJmrLgmjGAON7p\n4hIeerO7uazl+Uzq4ult23yoeAFV7cUMYpHBDh/XgxlQg/n7FITqCCIdmS2Z+Ii8\nFYaqItBJGBcDTevl6XRGsCaLcpzOmc1T68IKceykqKHLTCi9R//NBC8m1GpvzYKy\nAGktm03hcNviFDediGSkzbR8ClybIaAR/oKXqYA4QkhRWWiwQHOpRFqIxdZc18gR\n9QIDAQAB\n-----END PUBLIC KEY-----"

test:
  secret_key_base: 8d39ca3648b929b023f22a9102200a860d09cbfdc74a328cea1655302455d798571890daa07a53947066ca2401fcbc72f99c9105846b1ba7e3b6cab86391ea4d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "sss" %>
  aws_access_key_id: <%= ENV["S3_ACCESS_ID"] || "a" %>
  aws_secret_access_key: <%= ENV["S3_ACCESS_KEY"] || "aa" %>
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"]  || "feelingjy-staging" %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] || "" %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] || "" %>
  domain_name: <%= ENV["DOMAIN_NAME"]  || "feelingjy.herokuapp.com" %>
  tokbox:
    api_key: <%= ENV["OPENTOK_API_KEY"] %>
    secret: <%= ENV["OPENTOK_API_SECRETE"] %>
